// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BrunchTaskRunner
{
    static class Vsix
    {
        public const string Id = "b4a4ad37-5a4b-4dfd-85fd-595cab6a26a9";
        public const string Name = "Brunch Task Runner";
        public const string Description = @"Adds support for the Brunch build tool in Visual Studio's Task Runner Explorer.";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "Mads Kristensen";
        public const string Tags = "brunch, build";
    }
}
